name                'recursivedir'
maintainer          'Didar Bhullar'
maintainer_email    'didar.s.bhullar@gmail.com'
source_url          'https://github.com/Didar-Bhullar/recursivedir'
issues_url          'https://github.com/Didar-Bhullar/recursivedir/issues'
license             'Apache-2.0'
description         'Light wrapper around the directory resource for truley recursive builds.'
long_description    'Each directory gets the specified mode, owner, and
                     group instead of just the last leaf.'
version             '0.1.0'
chef_version        '>= 14.0'

supports 'debian'
supports 'ubuntu'
supports 'redhat'
supports 'centos'
supports 'fedora'
supports 'suse'
supports 'opensuse'
supports 'opensuseleap'
